### ISSUE TITLE
UI Enhancement: Cursor-Pointer

### ISSUE THREAD

**Issue by deezeddd** [jamdotdev/jam-dev-utilities#39]
##  The cursor can be changed to a pointer in the dropdown options to make it look good!

https://github.com/user-attachments/assets/52de1bd5-c2cd-41d0-bf31-de0b1e942fb6

**Comment by peckz** [comment]
@deezeddd Thanks for the feedback, good point, I'm gonna take care 👍

**Comment by deezeddd** [comment]
@peckz I can fix that, if there's no issue :)

**Comment by peckz** [comment]
@deezeddd Sure! Feel free to include it into that PR for image upload!
