### ISSUE TITLE
Feat: Image to Base64 - upload photos on click

### ISSUE THREAD

**Issue by deezeddd** [jamdotdev/jam-dev-utilities#40]
## Unable to upload photo maybe this needs a little fix

Steps to Reproduce:
   - Go To Jam Utilities
   - Select Image to Base64 converter
   - Try Uploading an image.
   
please have a look at the jam I made. 
https://jam.dev/c/82b7f959-6e91-445e-abad-34729f2375bf

**Comment by deezeddd** [comment]
#### Hi Jam Team, I would love to solve this issue.

**Comment by peckz** [comment]
@deezeddd Thanks for reaching out, currently users are only able to `drag n drop` images to selected area.

> Hi Jam Team, I would love to solve this issue.

Would you like to create a PR for it?

**Comment by deezeddd** [comment]
@peckz Surely! I'll work on it. Thanks
