### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by arunim2405** [jamdotdev/jam-dev-utilities#42]
Generating an electron app so its always accessible via the dock

**Comment by peckz** [comment]
@arunim2405 Thanks for reaching out, currently we don't have it as "planned feature", but I can see the use case. Until then, if you are using `MacOS`, I think you [can add website to dock](https://support.apple.com/guide/safari/add-to-dock-ibrw9e991864/mac#:~:text=In%20the%20Safari%20app%20on,Click%20Add.) with safari. It will feel like electron app. 
We would probably need to adjust Icon to look cool!
